import type { GenerationPhase } from './types';

export const copy = {
  appTitle: 'Scent Molecule Studio',
  appSubtitle: 'Structure analysis and candidate design for fragrance R&D.',
  analysis: 'Molecule analysis',
  candidates: 'Candidate design',
  dataIntake: 'Data intake',
  dataIntakeTitle: 'Sensory data intake',
  dataIntakeSubtitle: 'Record traceable observations without converting unassessed descriptors into negatives.',
  manualAssessment: 'Manual assessment',
  batchImport: 'CSV / XLSX import',
  experimentalContext: 'Experimental context',
  molecularIdentity: 'Molecular identity',
  sensoryObservation: 'Sensory observation',
  sourceProvenance: 'Source and provenance',
  validateRecord: 'Validate record',
  commitRecord: 'Commit assessment',
  validateFile: 'Validate file',
  commitImport: 'Commit validated import',
  downloadTemplate: 'Download template',
  chooseDataFile: 'Choose a CSV or XLSX file',
  validationPassed: 'Validation passed. The record is ready to commit.',
  validationFailed: 'Validation found issues that must be resolved before commit.',
  committed: 'Committed to an immutable dataset snapshot.',
  datasetVersions: 'Dataset snapshots',
  noSnapshots: 'No immutable snapshots have been created yet.',
  present: 'Present',
  absent: 'Absent',
  unassessed: 'Unassessed',
  intensity: 'Intensity',
  confidence: 'Confidence',
  traceabilityNote: 'Raw records are append-only. Corrections create a linked replacement record.',
  comingSoon: 'Coming soon',
  projects: 'Projects',
  library: 'Library',
  batchRuns: 'Batch runs',
  smiles: 'SMILES',
  analyze: 'Analyze molecule',
  structure2d: '2D structure',
  structure3d: 'Interactive 3D conformer ensemble',
  stereoResolution: 'Stereo resolution required',
  stereoExplanation: 'The molecular topology is known, but its stereochemical identity is not fully specified. Select one stereoisomer before odor prediction and 3D modeling.',
  stereoManual: 'This structure has more stereoisomers than the analysis limit. Enter a fully specified Isomeric SMILES using @, @@, / or \\.',
  selectStereoisomer: 'Use this stereoisomer',
  stereoOption: 'Stereoisomer',
  predictionLocked: 'Odor prediction is locked until stereochemistry is resolved.',
  conformerLocked: '3D modeling is locked until stereochemistry is resolved.',
  structuralIdentifiers: 'Structural identifiers',
  isomericSmiles: 'Isomeric SMILES',
  canonicalSmiles: 'Canonical SMILES',
  chemistryScreen: 'Chemistry screen',
  predictedProfile: 'Predicted odor profile',
  facets: 'Primary olfactory facets',
  textures: 'Olfactory textures',
  sensations: 'Sensations — incl. trigeminal',
  modelOutput: 'Model output',
  technicalDetails: 'Technical details',
  targetProfile: 'Target odor profile',
  diversity: 'Sampling diversity',
  generate: 'Generate candidates',
  stop: 'Stop run',
  running: 'Running',
  complete: 'Complete',
  loadingResources: 'Loading molecular resources',
  analyzingStructure: 'Analyzing structure',
  consent: (identifiers: string, providers: string) => `I understand that candidate ${identifiers} will be sent to ${providers} for identity checks.`,
  status: 'Generating and screening structures',
  statusSuccess: 'Five screened candidates are ready for ranking.',
  statusLimit: 'The screening limit was reached before five candidates passed all checks.',
  pubchemUnavailable: 'PubChem verification is currently unavailable. Unverified structures were not shortlisted.',
  referenceUnavailable: 'Reference verification is incomplete. Unverified structures were not shortlisted.',
  noCandidate: 'No structure passed all screening and identity checks in this run.',
  screeningLog: 'Screening log',
  statusEventsEmpty: 'Status events will appear here.',
  attempts: 'Attempts',
  failedScreen: 'Failed screen',
  referenceChecks: 'Reference checks',
  accepted: 'Accepted',
  acceptedForScoring: 'Accepted for scoring',
  acceptedProgress: 'Accepted candidate progress',
  events: 'events',
  rankedStructures: 'structures ranked by target fit.',
  shortlist: 'Shortlisted candidates',
  reviewQueue: 'Review queue',
  targetFit: 'Target fit',
  targetDescriptors: 'Target descriptors',
  supportingDescriptors: 'Supporting descriptors',
  emptyCandidates: 'Select one or more target descriptors, then generate a candidate set.',
  newLocal: 'New to local reference set',
  notFoundPubChem: 'Not found in PubChem',
  referenceEvidence: 'Reference evidence',
  noConfiguredMatch: 'No matching record found in the configured reference sources.',
  noMatchProvider: (provider: string) => `No match in ${provider}`,
  knownCatalog: 'Known in fragrance catalog',
  referenceReview: 'Reference verification review',
  academicEvidence: 'Academic evidence',
  academicEvidenceNotRun: 'Academic evidence is not run until stereochemistry is resolved.',
  academicExactMatch: 'Exact structure evidence found',
  academicReviewRequired: 'Structure evidence requires review',
  academicMentionOnly: 'Structure mention found',
  academicNoExact: 'No exact evidence found in the local academic index',
  academicNoMatches: 'No matching structure evidence is indexed for this query.',
  academicFullText: 'Full text',
  academicAbstract: 'Abstract fallback',
  academicOpenSource: 'Open source record',
  academicLocalIndex: 'Local index',
  academicUntitled: 'Untitled source',
  academicDoi: (doi: string) => `DOI: ${doi}`,
  academicPage: (page: number) => `Page ${page}`,
  academicChunk: (chunk: number) => `Chunk ${chunk}`,
  academicDescriptors: (descriptors: string[]) => `Descriptors: ${descriptors.join(', ')}`,
  academicBoundary: 'Evidence is citation-bound and does not establish safety, novelty or experimental validation.',
  academicUnreviewed: 'Unreviewed mention',
  academicAccepted: 'Reviewed evidence',
  academicUnassessed: 'Odor descriptors: unassessed',
  notConfigured: 'Not configured',
  ambiguousMatch: 'Ambiguous identifier match',
  unavailableCheck: 'Verification unavailable',
  exactStereo: 'Exact stereo identity',
  exactConnectivity: 'Exact connectivity',
  exactCas: 'Exact CAS',
  nameOnly: 'Name-only match',
  predictionNote: 'Predictions are model outputs intended for R&D guidance.',
  verificationNote: 'Reference checks report indexed identity or catalog evidence; they do not establish global novelty or patent clearance.',
  screenNote: 'The chemistry screen is not a toxicity, IFRA, synthesis or experimental volatility assessment.',
  invalidSmiles: 'This SMILES string could not be parsed. Check the structure and try again.',
  conformerUnavailable: '3D conformer unavailable',
  previousConformer: 'Previous conformer',
  nextConformer: 'Next conformer',
  conformerSelector: 'Select conformer',
  conformerOf: 'of',
  relativeEnergy: 'Relative energy',
  ensembleCaption: 'Computational conformer ensemble — not an experimental structure.',
  ensembleCounts: 'requested · embedded · converged',
  requestFailed: 'The request could not be completed.',
  unknownError: 'Unknown error',
  showDetails: 'Show details',
  selectDescriptors: 'Select descriptors',
  searchDescriptors: 'Search descriptors',
  searchTargetDescriptors: 'Search target descriptors',
  chemistryPass: 'Passed the configured screening profile',
  chemistryReview: 'Chemistry review required',
  chemistryReject: 'Outside the configured screening profile',
  macrocycleProfile: 'Macrocycle profile',
  formula: 'Formula',
  exactMw: 'Exact MW',
  logP: 'LogP',
  tpsa: 'TPSA',
  rotatableBonds: 'Rotatable bonds',
  heavyAtoms: 'Heavy atoms',
  saScore: 'SA score',
  volatilityTier: 'Estimated volatility tier',
  reviewCaption: 'These structures were not scored or shortlisted and require specialist review.',
  taxonomyAttribution: 'Osmo-compatible projection',
  taxonomyDisclaimer: 'No affiliation or endorsement is implied.',
  technicalOdorModel: 'Odor descriptor model: 2,048-bit chiral Morgan fingerprint.',
  technicalSampler: 'Candidate sampler: character-level sequence model.',
  technicalEvidence: 'Predictions are not experimental sensory evidence.',
  modelVersion: 'Model version',
  datasetVersion: 'Dataset version',
  calibration: 'Calibration',
  reliability: 'Evidence domain',
  nearestSimilarity: 'Nearest training similarity',
  uncalibrated: 'Uncalibrated legacy output',
  inDomain: 'In domain',
  limitedEvidence: 'Limited evidence',
  outOfDomain: 'Out of domain',
  chemesthesis: 'Chemesthesis',
  candidate: 'Candidate',
  download2d: 'Download 2D structure',
  fullscreen2d: 'View 2D structure fullscreen',
  reset3d: 'Reset 3D view',
  fullscreen3d: 'View 3D conformer fullscreen',
  workspaceNavigation: 'Workspace navigation',
  mobileNavigation: 'Mobile workspace navigation',
  openNavigation: 'Open navigation',
  closeNavigation: 'Close navigation',
  colorTheme: 'Color theme',
  rdWorkspace: 'R&D workspace',
  version: 'Version 0.5',
  light: 'Light',
  dark: 'Dark',
  system: 'System'
} as const;

export const intakeFields = {
  studyName: 'Study name',
  sessionName: 'Session',
  assessorId: 'Pseudonymous assessor ID',
  blindedSampleCode: 'Blinded sample code',
  smiles: 'SMILES',
  descriptor: 'Odor descriptor',
  presenceState: 'Assessment state',
  concentration: 'Concentration',
  concentrationUnit: 'Unit',
  solvent: 'Solvent',
  temperature: 'Temperature (°C)',
  preparationTime: 'Preparation time (minutes)',
  replicate: 'Replicate',
  sourceName: 'Source',
  sourceVersion: 'Source version',
  sourceLicense: 'License',
  notes: 'Notes',
  fileRequirements: 'CSV and XLSX files are validated for structure, units, descriptor vocabulary, duplicates, stereo and identifier conflicts before commit.',
  preview: 'Normalized preview',
  validationIssues: 'Validation issues',
  records: 'records',
  valid: 'valid',
  errors: 'errors',
  warnings: 'warnings'
} as const;

export const phaseCopy: Record<GenerationPhase, string> = {
  SAMPLING: 'Sampling structure',
  INVALID: 'Invalid SMILES',
  DUPLICATE: 'Duplicate in local reference set',
  REJECTED: 'Failed chemistry screen',
  REVIEW: 'Sent to chemistry review',
  PUBCHEM_CHECK: 'Checking PubChem identity',
  PUBCHEM_FOUND: 'PubChem match found',
  PUBCHEM_UNVERIFIED: 'PubChem verification unavailable',
  CHECKING_REFERENCES: 'Checking configured reference sources',
  CATALOG_MATCH: 'Fragrance catalog match found',
  REFERENCE_UNVERIFIED: 'Reference verification requires review',
  REFERENCE_ACCEPTED: 'Reference checks accepted',
  ACCEPTED: 'Accepted for scoring',
  STEREO_ENUMERATION: 'Resolving stereoisomers',
  STEREO_REVIEW: 'Stereo variants require chemistry review',
  RANKING: 'Ranking target fit',
  PREPARING_3D: 'Preparing 3D conformers'
};

export const chemesthesis = new Set([
  'Cooling',
  'Cold/Crisp/Fresh',
  'Heaty/Hot',
  'Harsh',
  'Scratchy',
  'Strong/Pungent/Sharp'
]);
